import { useState } from "react";
import type { FormEvent } from "react";
import type { AddVolumeInput, EditionDetail } from "../domain/model";

export function AddVolumeView({ edition, busy, onCancel, onSave }: { edition: EditionDetail; busy: boolean; onCancel: () => void; onSave: (input: AddVolumeInput) => Promise<void> }) {
  const suggestion = String(Math.max(0, ...edition.volumes.map((v) => /^\d+$/.test(v.displayLabel) ? Number(v.displayLabel) : 0)) + 1);
  const [label, setLabel] = useState(suggestion); const [isbn, setIsbn] = useState(""); const [status, setStatus] = useState<"released" | "upcoming" | "unknown">("released"); const [owned, setOwned] = useState(false); const [read, setRead] = useState(false); const [wish, setWish] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); if (!label.trim()) { setError("請輸入卷數，例如 12、12.5、外傳。"); return; } await onSave({ displayLabel: label.trim(), isbn: isbn.trim() || null, availabilityStatus: status, collection: { isOwned: owned, isRead: read, isWishlisted: owned ? false : wish, purchasePriceAmount: null, purchasePriceCurrency: null, acquiredOn: null, condition: "unknown", storageLocation: null, notes: null } }); }
  return <div className="page form-page"><button className="back" onClick={onCancel}>← 取消新增</button><header className="page-heading compact"><div><p className="eyebrow">{edition.name}</p><h1>新增卷冊</h1><p>連載新出版時，在這裡加入下一卷或外傳。</p></div></header><form className="add-form" onSubmit={(e) => void submit(e)}><label className="field"><span>卷數／標籤 *</span><input value={label} onChange={(e) => setLabel(e.target.value)} placeholder="例如 12、12.5、外傳" /></label><label className="field"><span>ISBN</span><input value={isbn} onChange={(e) => setIsbn(e.target.value)} /></label><label className="field"><span>出版狀態</span><select value={status} onChange={(e) => setStatus(e.target.value as typeof status)}><option value="released">已出版</option><option value="upcoming">即將出版</option><option value="unknown">未知</option></select></label><div className="field collection-checks"><span>收藏狀態</span><label><input type="checkbox" checked={owned} onChange={(e) => { setOwned(e.target.checked); if (e.target.checked) setWish(false); }} /> 擁有</label><label><input type="checkbox" checked={read} onChange={(e) => setRead(e.target.checked)} /> 已讀</label><label><input type="checkbox" checked={wish} disabled={owned} onChange={(e) => setWish(e.target.checked)} /> 願望</label></div>{error && <p className="form-error">{error}</p>}<div className="form-actions"><button type="button" className="secondary" onClick={onCancel}>取消</button><button className="primary" disabled={busy}>{busy ? "新增中…" : "新增卷冊"}</button></div></form></div>;
}
