import { useState } from "react";
import type { FormEvent } from "react";
import type { SeriesDetail, UpdateSeriesMetadataInput } from "../domain/model";

export function EditSeriesView({ series, busy, onCancel, onSave, onChooseCover, onRemoveCover }: { series: SeriesDetail; busy: boolean; onCancel: () => void; onSave: (input: UpdateSeriesMetadataInput) => Promise<void>; onChooseCover: () => Promise<void>; onRemoveCover: () => Promise<void> }) {
  const edition = series.editions[0];
  const [form, setForm] = useState({ title: series.title, originalTitle: series.originalTitle || "", description: series.description || "", publicationStatus: series.publicationStatus, author: series.contributors[0]?.name || "", editionName: edition.name, publisher: edition.publisher });
  const [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); if (!form.title.trim() || !form.author.trim() || !form.publisher.trim() || !form.editionName.trim()) { setError("系列名稱、作者、出版社和版本名稱不可空白。"); return; } await onSave({ ...form, originalTitle: form.originalTitle.trim() || null, description: form.description.trim() || null, editionId: edition.id }); }
  const field = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  return <div className="page form-page"><button className="back" onClick={onCancel}>← 取消編輯</button><header className="page-heading compact"><div><p className="eyebrow">系列資料</p><h1>編輯漫畫</h1></div></header><div className="cover-tools"><button className="secondary" onClick={() => void onChooseCover()}>選擇真正封面</button>{series.representativeCover && <button className="secondary" onClick={() => void onRemoveCover()}>移除封面</button>}<small>支援 JPG、PNG、WebP，最大 10 MiB</small></div><form className="add-form" onSubmit={(event) => void submit(event)}><label className="field"><span>系列名稱 *</span><input value={form.title} onChange={(e) => field("title", e.target.value)} /></label><label className="field"><span>作者 *</span><input value={form.author} onChange={(e) => field("author", e.target.value)} /></label><label className="field"><span>出版社 *</span><input value={form.publisher} onChange={(e) => field("publisher", e.target.value)} /></label><label className="field"><span>版本名稱 *</span><input value={form.editionName} onChange={(e) => field("editionName", e.target.value)} /></label><label className="field"><span>原文名稱</span><input value={form.originalTitle} onChange={(e) => field("originalTitle", e.target.value)} /></label><label className="field"><span>連載狀態</span><select value={form.publicationStatus} onChange={(e) => field("publicationStatus", e.target.value)}><option value="ongoing">連載中</option><option value="completed">已完結</option><option value="hiatus">休刊中</option><option value="unknown">未知</option></select></label><label className="field wide"><span>簡介</span><textarea rows={5} value={form.description} onChange={(e) => field("description", e.target.value)} /></label>{error && <p className="form-error">{error}</p>}<div className="form-actions"><button type="button" className="secondary" onClick={onCancel}>取消</button><button className="primary" disabled={busy}>{busy ? "儲存中…" : "儲存修改"}</button></div></form></div>;
}
